apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: anotherone
  name: anotherone
spec:
  containers:
  - image: pavan5107/k8s:alpine-nomagento
    name: anotherone
    resources: {}
    envFrom:
    - configMapRef:
        name: anotherone
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
